name: Daily Open Food Facts Scraper

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scrape_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This grants write access to the repository content

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Change to working directory and run Open Food Facts scraper
        run: |
          cd ${{ github.workspace }}
          python openfoodfacts_scraper.py

      - name: Commit and push updated CSVs
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # --- NEW: Tell Git to assume streamlit_app.py is unchanged for this commit ---
          # This prevents conflicts with local changes to streamlit_app.py
          git update-index --assume-unchanged streamlit_app.py
          
          # Add the Open Food Facts generated CSV file
          git add openfoodfacts_breakfast_products.csv
          
          # Commit only if there are changes (excluding streamlit_app.py)
          git diff --quiet --exit-code || git commit -m 'Automated Open Food Facts data update [skip ci]'
          
          # Push changes
          git push
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
